spring:
  datasource:
    url: jdbc:h2:mem:allianz;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
flyway:
  url: jdbc:h2:mem:allianz
  user: sa
  password: password
event:
  start-day: "09:00"
  finish-day: "17:00"
